PROJECT_NAME = 'Jiyu Immunodeficiency Virus'
MAJOR_VER, MINOR_VER = 0, 2
RELEASE_STAGE = 'b1'
VERSION = f'{MAJOR_VER}.{MINOR_VER}{RELEASE_STAGE}'
FULL_VERSION = f'{PROJECT_NAME} v{VERSION}'
UPDATE_URL = "https://api.github.com/repos/Errorsia/PJIV-pre/releases/latest"
E_CLASSROOM_NAME = 'studentmain.exe'
# CODE_NAME = ''
# NICKNAME = ''